# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    portiny.rabbitmq.aliases:
        Sitemap: App\Service\Rabbit\SitemapConsumer
        portiny.rabbitmq.connection:
            host: '%env(RABBIT_HOST)%'
            port: '%env(RABBIT_PORT)%'
            user: '%env(RABBIT_USER)%'
            password: '%env(RABBIT_PASSWORD)%'
            timeout: '1'
            heartbeat: '60.0'
            persistent: 'false'
            path: '/'
            tcp_nodelay: 'false'
        projectDir: '%kernel.project_dir%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $environment: '%kernel.environment%'
            $consolePath: '%kernel.project_dir%/bin/console'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DTO,VO,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\Rabbit\SitemapExchange: ~
    App\Service\Rabbit\SitemapQueue: ~
    App\Service\Rabbit\SitemapProducer: ~
    App\Service\Rabbit\SitemapConsumer: ~

    _instanceof:
        Portiny\RabbitMQ\Consumer\AbstractConsumer:
            tags: ['portiny.rabbitmq.consumer']
        Portiny\RabbitMQ\Exchange\AbstractExchange:
            tags: ['portiny.rabbitmq.exchange']
        Portiny\RabbitMQ\Producer\AbstractProducer:
            tags: ['portiny.rabbitmq.producer']
        Portiny\RabbitMQ\Queue\AbstractQueue:
            tags: ['portiny.rabbitmq.queue']